title: Len Koepsell
profession: Playwright
email: info@lenkoepsell.com
phone_number: (213) 282-7480
collections:
  plays:
    output: true
    permalink: /plays/:path
exclude: [CNAME, Gemfile*]
defaults:
  - scope:
      path: ''
      type: plays
    values:
      layout: play
  - scope:
      path: ''
    values:
      layout: default
